import React from 'react';
import { Text, View } from '@react-pdf/renderer';
import { styles } from '../styles';
import { formatText } from '../../../utils/reportUtils';

interface NotesDeclarationSectionProps {
    generatedBy: string;
}

export const NotesDeclarationSection: React.FC<NotesDeclarationSectionProps> = ({ generatedBy }) => (
    <View style={styles.section}>
        <Text style={styles.h2}>OFFICIAL REMARKS & DECLARATION</Text>

        {/* Notes Box */}
        <View style={{ minHeight: 80, borderStyle: 'dotted', borderWidth: 1, borderColor: '#94a3b8', padding: 8, marginTop: 10, marginBottom: 20 }}>
            <Text style={[styles.small, { color: '#64748b' }]}>Case Officer Notes:</Text>
        </View>

        <Text style={[styles.text, { marginBottom: 40, fontSize: 9, fontStyle: 'italic', color: '#475569', lineHeight: 1.6 }]}>
            I hereby certify that the information provided in this report is extracted directly from the Central Candidate Management System and reflects the accurate status of the candidate as of the generated date. This document is system-generated and remains official for all internal and administrative purposes.
        </Text>

        <View style={[styles.row, { justifyContent: 'space-between' }]}>
            {/* Signature Area 1 */}
            <View style={{ width: '45%' }}>
                <View style={{ borderBottomWidth: 1.5, borderBottomColor: '#000', marginBottom: 6, height: 40 }}></View>
                <Text style={[styles.text, { fontSize: 10.5, fontFamily: 'Helvetica-Bold' }]}>Authorized Signature</Text>
                <Text style={[styles.small, { color: '#64748b' }]}>Manager - Operations</Text>
            </View>

            {/* Signature Area 2 */}
            <View style={{ width: '45%' }}>
                <View style={{ borderBottomWidth: 1.5, borderBottomColor: '#000', marginBottom: 6, height: 40 }}></View>
                <Text style={[styles.text, { fontSize: 10.5, fontFamily: 'Helvetica-Bold' }]}>Generated By: {formatText(generatedBy)}</Text>
                <Text style={[styles.small, { color: '#64748b' }]}>System Administrator</Text>
            </View>
        </View>
    </View>
);
