import React from 'react';
import { Text, View } from '@react-pdf/renderer';
import { styles } from '../styles';
import { formatText } from '../../../utils/reportUtils';

interface NotesDeclarationSectionProps {
    generatedBy: string;
}

export const NotesDeclarationSection: React.FC<NotesDeclarationSectionProps> = ({ generatedBy }) => (
    <View style={styles.section}>
        <Text style={styles.h2}>Official Remarks & Declaration</Text>

        <View style={{ minHeight: 60, border: '1px dashed #ccc', padding: 5, marginBottom: 15 }}>
            <Text style={[styles.small, { color: '#999' }]}>Case Officer Notes:</Text>
        </View>

        <Text style={[styles.text, { marginBottom: 30, fontSize: 9, fontStyle: 'italic', color: '#475569' }]}>
            I hereby certify that the information provided in this report is extracted directly from the Central Candidate Management System and reflects the accurate status of the candidate as of the generated date. This document is system-generated and remains official for all internal and administrative purposes.
        </Text>

        <View style={styles.row}>
            {/* Authorized Sig Area */}
            <View style={{ width: '50%', paddingRight: 20 }}>
                <View style={{ borderBottomWidth: 1, borderBottomColor: '#000', marginBottom: 5, height: 40 }}></View>
                <Text style={styles.text}>Authorized Signature</Text>
                <Text style={styles.small}>Manager - Operations</Text>
            </View>

            <View style={{ width: '50%', paddingLeft: 20 }}>
                <View style={{ borderBottomWidth: 1, borderBottomColor: '#000', marginBottom: 5, height: 40 }}></View>
                <Text style={styles.text}>Generated By: {formatText(generatedBy)}</Text>
                <Text style={styles.small}>System Administrator</Text>
            </View>
        </View>
    </View>
);
