import React from 'react';
import { Document, Page, Text, View, Image } from '@react-pdf/renderer';
import { styles } from './styles';
import { Candidate } from '@/types';
import { HeaderSection } from './sections/HeaderSection';
import { CandidateIdentitySection } from './sections/CandidateIdentitySection';
import { JobInfoSection } from './sections/JobInfoSection';
import { WorkflowStatusSection } from './sections/WorkflowStatusSection';
import { ComplianceSection } from './sections/ComplianceSection';
import { DocumentStatusTable } from './sections/DocumentStatusTable';
import { FinancialSummarySection } from './sections/FinancialSummarySection';
import { NotesDeclarationSection } from './sections/NotesDeclarationSection';
import { FamilySection } from './sections/FamilySection';
import { BureauSection } from './sections/BureauSection';
import { AIExecutiveSummarySection } from './sections/AIExecutiveSummarySection';
import { ComplianceSnapshot } from './sections/ComplianceSnapshot';

import { SystemReport } from '../../../services/reportService';
import logo from './logo_suhara.jpg';

interface CandidateReportPDFProps {
    candidate: Candidate;
    reportId: string;
    generatedBy: string;
    systemReport?: SystemReport;
}

export const CandidateReportPDF: React.FC<CandidateReportPDFProps> = ({ candidate, reportId, generatedBy, systemReport }) => (
    <Document>
        <Page size="A4" style={styles.page}>

            {/* LAYER 1: WATERMARK (Background) - Fixed Position Behind Content */}
            <View style={styles.watermarkContainer} fixed>
                <Image src={logo} style={styles.watermarkImage} />
                <Text style={styles.watermarkText}>
                    CONFIDENTIAL AUDIT TRAIL | Report ID: {reportId} | Generated By: {generatedBy} | Date: {new Date().toLocaleDateString()}
                </Text>
            </View>

            {/* LAYER 2: FOOTER (Foreground/Fixed) - Absolute Positioned on Top */}
            <View style={styles.footer} fixed>
                <Text style={styles.footerText}>
                    Suhara Foreign Employment Agency | License No: GWA-2024-8892 | www.suhara.lk
                </Text>
                <Text style={styles.pageNumber}
                    render={({ pageNumber, totalPages }) =>
                        `Page ${pageNumber} of ${totalPages}`
                    }
                    fixed
                />
            </View>

            {/* LAYER 3: CONTENT FLOW */}

            {/* Header */}
            <HeaderSection
                reportId={reportId}
                generatedAt={new Date().toLocaleString()}
                candidateId={candidate.id}
            />

            {/* AI Executive Summary - HIGHLIGHT OF THE V2 ENGINE */}
            {systemReport && <AIExecutiveSummarySection systemReport={systemReport} />}

            {/* Compliance Snapshot */}
            <ComplianceSnapshot candidate={candidate} />

            {/* Main Sections */}
            <CandidateIdentitySection candidate={candidate} />
            <JobInfoSection candidate={candidate} />
            <WorkflowStatusSection candidate={candidate} />
            <BureauSection candidate={candidate} />
            <FamilySection candidate={candidate} />
            <ComplianceSection candidate={candidate} />
            <DocumentStatusTable candidate={candidate} />
            <FinancialSummarySection candidate={candidate} />

            {/* Declaration & Signature */}
            <NotesDeclarationSection generatedBy={generatedBy} />

        </Page>
    </Document>
);
