import React from 'react';
import { Document, Page, Text, View, Image } from '@react-pdf/renderer';
import { styles } from './styles';
import { Candidate } from '@/types';
import { HeaderSection } from './sections/HeaderSection';
import { CandidateIdentitySection } from './sections/CandidateIdentitySection';
import { JobInfoSection } from './sections/JobInfoSection';
import { ComplianceSnapshot } from './sections/ComplianceSnapshot';
import { FinancialSummarySection } from './sections/FinancialSummarySection';
import { NotesDeclarationSection } from './sections/NotesDeclarationSection';
import { FamilySection } from './sections/FamilySection';
import { BureauSection } from './sections/BureauSection';
import { ComplianceSection } from './sections/ComplianceSection';
import { DocumentStatusTable } from './sections/DocumentStatusTable';
import { WorkflowStatusSection } from './sections/WorkflowStatusSection';

import { SystemReport } from '../../../services/reportService';
import logo from './logo_suhara.jpg';

interface CandidateReportPDFProps {
    candidate: Candidate;
    reportId: string;
    generatedBy: string;
    systemReport?: SystemReport;
}

export const CandidateReportPDF: React.FC<CandidateReportPDFProps> = ({ candidate, reportId, generatedBy, systemReport }) => (
    <Document>
        {/* PAGE 1: EXECUTIVE SUMMARY */}
        <Page size="A4" style={styles.page}>
            {/* BACKGROUND LAYER */}
            <View style={styles.watermarkContainer} fixed>
                <Image src={logo} style={styles.watermarkImage} />
                <Text style={styles.watermarkText}>
                    CONFIDENTIAL AUDIT TRAIL | Report ID: {reportId} | Generated By: {generatedBy} | Date: {new Date().toLocaleDateString()}
                </Text>
            </View>

            {/* Header */}
            <HeaderSection
                reportId={reportId}
                generatedAt={new Date().toLocaleString()}
                candidateId={candidate.id}
            />

            {/* Compliance Snapshot (High Level) */}
            <ComplianceSnapshot candidate={candidate} />

            {/* Core Candidate Info */}
            <CandidateIdentitySection candidate={candidate} />

            <JobInfoSection candidate={candidate} />

            {/* Basic Financial Summary */}
            <FinancialSummarySection candidate={candidate} />

            {/* Declaration & Signature on First Page for Official Use */}
            <NotesDeclarationSection generatedBy={generatedBy} />
        </Page>

        {/* PAGE 2: COMPREHENSIVE DETAILS */}
        <Page size="A4" style={styles.page}>
            <View style={styles.watermarkContainer} fixed>
                <Image src={logo} style={styles.watermarkImage} />
                <Text style={styles.watermarkText}>
                    CONFIDENTIAL AUDIT TRAIL | Report ID: {reportId} | Candidate ID: {candidate.id}
                </Text>
            </View>

            <Text style={styles.h2}>DETAILED BIO-DATA & FAMILY INFO</Text>
            <FamilySection candidate={candidate} />

            <View style={{ marginTop: 20 }}>
                <BureauSection candidate={candidate} />
            </View>

            <View style={{ marginTop: 20 }}>
                <ComplianceSection candidate={candidate} />
            </View>
        </Page>

        {/* PAGE 3: WORKFLOW & SYSTEM LOGS */}
        <Page size="A4" style={styles.page}>
            <View style={styles.watermarkContainer} fixed>
                <Image src={logo} style={styles.watermarkImage} />
                <Text style={styles.watermarkText}>
                    CONFIDENTIAL AUDIT TRAIL | Report ID: {reportId} | System Log Page
                </Text>
            </View>

            <WorkflowStatusSection candidate={candidate} />

            <View style={{ marginTop: 20 }}>
                <DocumentStatusTable candidate={candidate} />
            </View>

            {/* System Info Section */}
            {systemReport && (
                <View style={[styles.section, { marginTop: 20 }]}>
                    <Text style={styles.h2}>SYSTEM DATA & AUDIT LOGS</Text>
                    <View style={styles.table}>
                        <View style={[styles.tableRow, styles.tableHeader]}>
                            <Text style={[styles.tableCell, { width: '40%' }]}>Audit event</Text>
                            <Text style={[styles.tableCell, { width: '30%' }]}>User</Text>
                            <Text style={[styles.tableCell, styles.lastCell, { width: '30%' }]}>Timestamp</Text>
                        </View>
                        <View style={styles.tableRow}>
                            <Text style={[styles.tableCell, { width: '40%' }]}>Report Generated</Text>
                            <Text style={[styles.tableCell, { width: '30%' }]}>{generatedBy}</Text>
                            <Text style={[styles.tableCell, styles.lastCell, { width: '30%' }]}>{new Date().toLocaleString()}</Text>
                        </View>
                        {/* Add more system metrics if systemReport contains them */}
                        <View style={styles.tableRow}>
                            <Text style={[styles.tableCell, { width: '40%' }]}>Data Integrity Check</Text>
                            <Text style={[styles.tableCell, { width: '30%' }]}>SYSTEM</Text>
                            <Text style={[styles.tableCell, styles.lastCell, { width: '30%' }]}>PASSED</Text>
                        </View>
                    </View>
                </View>
            )}
        </Page>
    </Document>
);
