import React from 'react';
import { Document, Page, Text, View, Image } from '@react-pdf/renderer';
import { styles } from './styles';
import { Candidate, AdvancePayment } from '@/types';
import { SystemReport } from '../../../services/reportService';
import logo from './logo_suhara.jpg';

interface CandidateReportPDFProps {
    candidate: Candidate;
    reportId: string;
    generatedBy: string;
    systemReport?: SystemReport;
}

const TableRow = ({ label, value, colSpan = 1, isLast = false, isAlert = false, isSuccess = false, isBold = false }: any) => {
    const valueStyle = [
        styles.tableCellValue,
        colSpan === 3 ? styles.colFull : undefined,
        colSpan === 2 ? styles.colHalf : undefined,
        isLast ? styles.lastCell : undefined,
        isAlert ? styles.alertText : undefined,
        isSuccess ? styles.successText : undefined,
        isBold ? styles.boldValue : undefined
    ].filter(Boolean) as any;
    return (
        <>
            <View style={styles.tableCellLabel}><Text>{label}</Text></View>
            <View style={valueStyle}><Text>{value || 'N/A'}</Text></View>
        </>
    );
};

const Header = ({ candidate, reportId }: { candidate: Candidate, reportId: string }) => (
    <View style={styles.headerContainer} fixed>
        <Image src={logo} style={styles.logo} />
        <View style={styles.headerText}>
            <View style={{ alignItems: 'flex-end', marginBottom: 6 }}>
                {candidate.complianceFlags?.some(f => !f.isResolved && f.severity === 'CRITICAL') ? (
                    <View style={{ backgroundColor: '#fef2f2', padding: '2 6', borderRadius: 2, border: '1 solid #ef4444' }}>
                        <Text style={{ fontSize: 7, fontFamily: 'Helvetica-Bold', color: '#dc2626' }}>CRITICAL COMPLIANCE ISSUE</Text>
                    </View>
                ) : (candidate.complianceFlags && candidate.complianceFlags.some(f => !f.isResolved)) ? (
                    <View style={{ backgroundColor: '#fffbeb', padding: '2 6', borderRadius: 2, border: '1 solid #f59e0b' }}>
                        <Text style={{ fontSize: 7, fontFamily: 'Helvetica-Bold', color: '#b45309' }}>COMPLIANCE WARNING</Text>
                    </View>
                ) : (
                    <View style={{ backgroundColor: '#f0fdf4', padding: '2 6', borderRadius: 2, border: '1 solid #22c55e' }}>
                        <Text style={{ fontSize: 7, fontFamily: 'Helvetica-Bold', color: '#16a34a' }}>VERIFIED COMPLIANT</Text>
                    </View>
                )}
            </View>
            <Text style={styles.docTitle}>Candidate Status Report</Text>
            <Text style={styles.docMetaBold}>REG NO: {candidate.regNo || candidate.candidateCode}</Text>
            <Text style={styles.docMeta}>CODE: {candidate.candidateCode} | GEN: {new Date().toLocaleString()}</Text>
            <Text style={styles.docMeta}>REPORT ID: {reportId}</Text>
        </View>
    </View>
);

const Footer = ({ generatedBy }: { generatedBy: string }) => (
    <View style={styles.footer} fixed>
        <Text style={styles.footerText}>CONFIDENTIAL</Text>
        <Text style={styles.footerText} render={({ pageNumber, totalPages }) => (`PAGE ${pageNumber} OF ${totalPages}`)} />
        <Text style={styles.footerText}>GENERATED BY: {generatedBy.toUpperCase()}</Text>
    </View>
);

const Watermark = () => (
    <Image src={logo} style={styles.watermark} fixed />
);

export const CandidateReportPDF: React.FC<CandidateReportPDFProps> = ({ candidate, reportId, generatedBy, systemReport }) => {

    return (
        <Document>
            <Page size="A4" style={styles.page}>
                <Header candidate={candidate} reportId={reportId} />
                <Footer generatedBy={generatedBy} />
                <Watermark />

                {/* 1. Registration Details */}
                <Text style={styles.sectionTitle}>1. Registration Details</Text>
                <View style={styles.table}>
                    <View style={styles.tableRow}>
                        <TableRow label="System ID" value={candidate.id} />
                        <TableRow label="Candidate Code" value={candidate.candidateCode} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="REG NO." value={candidate.regNo} isBold />
                        <TableRow label="Registration Date" value={candidate.regDate ? new Date(candidate.regDate).toLocaleDateString() : ''} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Assigned Stage" value={candidate.stage} isAlert={candidate.stageStatus === 'Rejected' || candidate.stageStatus === 'Cancelled'} />
                        <TableRow label="Stage Status" value={candidate.stageStatus} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Stage Date" value={candidate.stageEnteredAt ? new Date(candidate.stageEnteredAt).toLocaleString() : 'N/A'} />
                        <TableRow label="Profile Type" value={`${candidate.profileType || 'N/A'} (${candidate.profileCompletionPercentage || 0}%)`} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Coordinator" value={candidate.coordinatorName} />
                        <TableRow label="Document Officer" value={candidate.dhOfficer} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Foreign Agent" value={candidate.foreignAgent} />
                        <TableRow label="Company" value={candidate.companyName} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Batch Reference" value={candidate.batchReference} />
                        <TableRow label="Ref No" value={candidate.refNo} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Office Officer" value={candidate.officeUseOnly?.customerCareOfficer} />
                        <TableRow label="File Officer" value={candidate.officeUseOnly?.fileHandlingOfficer} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Office Charges" value={candidate.officeUseOnly?.charges} />
                        <TableRow label="Office Date" value={candidate.officeUseOnly?.date} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Application Date" value={candidate.applicationDate ? new Date(candidate.applicationDate).toLocaleDateString() : 'N/A'} />
                        <TableRow label="Office Selection" value={candidate.officeSelection} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Office Remark" value={candidate.officeRemark} />
                        <TableRow label="Notes" value={candidate.notes} isLast />
                    </View>
                </View>

                {/* 2. PRIMARY IDENTITY MATRIX */}
                <Text style={styles.sectionTitle}>2. Personal Information</Text>
                <View style={styles.table}>
                    <View style={styles.tableRow}>
                        <TableRow label="Full Name" value={candidate.personalInfo?.fullName || candidate.name} colSpan={3} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="First Name" value={candidate.personalInfo?.firstName || candidate.firstName} />
                        <TableRow label="Surname" value={candidate.personalInfo?.surname || candidate.surname} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Middle Name" value={candidate.personalInfo?.middleName || candidate.middleName} />
                        <TableRow label="Other Names" value={candidate.personalInfo?.otherNames || candidate.otherNames} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="NIC" value={candidate.personalInfo?.nic || candidate.nic} />
                        <TableRow label="Date of Birth" value={`${candidate.personalInfo?.dob || candidate.dob || 'N/A'} (${candidate.personalInfo?.age || 'N/A'} yrs)`} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Gender / Marital" value={`${candidate.personalInfo?.gender || candidate.gender || 'N/A'} / ${candidate.personalInfo?.maritalStatus || candidate.personalInfo?.civilStatus || candidate.maritalStatus || 'N/A'}`} />
                        <TableRow label="Nationality" value={`${candidate.personalInfo?.nationality || candidate.nationality || 'N/A'} / ${candidate.personalInfo?.religion || candidate.religion || 'N/A'}`} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Height / Weight" value={`${candidate.personalInfo?.height?.feet || 0}'${candidate.personalInfo?.height?.inches || 0}" / ${candidate.personalInfo?.weight || '-'} kg`} />
                        <TableRow label="Driving License" value={candidate.personalInfo?.drivingLicenseNo || candidate.drivingLicenseNo || 'N/A'} isLast />
                    </View>
                </View>

                {/* 3. COMMUNICATION & TRACEABILITY */}
                <Text style={styles.sectionTitle}>3. Contact Details</Text>
                <View style={styles.table}>
                    <View style={styles.tableRow}>
                        <TableRow label="Phone" value={candidate.contactInfo?.primaryPhone || candidate.phone} />
                        <TableRow label="WhatsApp" value={candidate.contactInfo?.whatsappPhone || candidate.whatsapp || 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Secondary Phone" value={candidate.secondaryPhone} />
                        <TableRow label="Other Phones" value={candidate.contactInfo?.additionalPhones?.join(', ') || candidate.additionalContactNumbers?.join(', ')} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Email" value={candidate.contactInfo?.email || candidate.email} />
                        <TableRow label="Secondary Email" value={candidate.secondaryEmail} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Address" value={candidate.personalInfo?.address || candidate.address} colSpan={3} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="City / Province" value={`${candidate.personalInfo?.city || candidate.city || 'N/A'} / ${candidate.personalInfo?.province || candidate.province || 'N/A'}`} />
                        <TableRow label="District" value={candidate.personalInfo?.district || candidate.district || 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="GS Division" value={`${candidate.personalInfo?.gsDivision || candidate.gsDivision || 'N/A'} / ${candidate.personalInfo?.divisionalSecretariat || candidate.divisionalSecretariat || 'N/A'}`} colSpan={3} isLast />
                    </View>
                </View>

                {/* 4. Family & Emergency */}
                <Text style={styles.sectionTitle}>4. Family & Emergency</Text>
                <View style={styles.table}>
                    <View style={styles.tableRow}>
                        <TableRow label="Emergency Contact" value={`${candidate.contactInfo?.emergencyContact?.name || 'N/A'} (${candidate.contactInfo?.emergencyContact?.relation || 'N/A'}) - ${candidate.contactInfo?.emergencyContact?.phone || 'N/A'}`} colSpan={3} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Emergency Address" value={candidate.contactInfo?.emergencyContact?.address} colSpan={3} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Father" value={`${candidate.personalInfo?.fatherName || candidate.fatherName || 'N/A'}${candidate.fatherAge ? ' (Age: ' + candidate.fatherAge + ')' : ''}${candidate.fatherNic ? ' NIC: ' + candidate.fatherNic : ''}`} colSpan={3} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Mother" value={`${candidate.personalInfo?.motherName || candidate.motherName || 'N/A'}${candidate.motherAge ? ' (Age: ' + candidate.motherAge + ')' : ''}${candidate.motherNic ? ' NIC: ' + candidate.motherNic : ''}`} colSpan={3} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Spouse" value={`${candidate.personalInfo?.spouseName || candidate.spouseName || 'N/A'}${candidate.spouseAge ? ' (Age: ' + candidate.spouseAge + ')' : ''}${candidate.spouseNic ? ' NIC: ' + candidate.spouseNic : ''}`} />
                        <TableRow label="Children" value={candidate.personalInfo?.children?.length || candidate.numberOfChildren || '0'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Guardian" value={`${candidate.guardianName || 'N/A'} (ID: ${candidate.guardianIdNo || 'N/A'}) - ${candidate.guardianContact || 'N/A'}`} colSpan={3} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Guardian DOB" value={candidate.guardianBirthday} colSpan={3} isLast />
                    </View>
                </View>

            </Page>

            <Page size="A4" style={styles.page}>
                <Header candidate={candidate} reportId={reportId} />
                <Footer generatedBy={generatedBy} />
                <Watermark />

                {/* 5. Passport Details */}
                <Text style={styles.sectionTitle}>5. Passport Details</Text>
                <View style={styles.table}>
                    <View style={styles.tableRow}>
                        <TableRow label="Passport Number" value={candidate.passportData?.passportNumber} />
                        <TableRow label="Issue Date" value={candidate.passportData?.issuedDate ? new Date(candidate.passportData.issuedDate).toLocaleDateString() : ''} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Issuing Country" value={candidate.passportData?.country} />
                        <TableRow label="Expiry Date" value={candidate.passportData?.expiryDate ? new Date(candidate.passportData.expiryDate).toLocaleDateString() : ''} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Place of Birth" value={candidate.personalInfo?.placeOfBirth || candidate.placeOfBirth || 'N/A'} />
                        <TableRow label="Profession" value={candidate.personalInfo?.passportProfession || candidate.passportProfession || 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Passport Status" value={candidate.passportData?.status} isSuccess={candidate.passportData?.status === 'VALID'} isAlert={candidate.passportData?.status === 'EXPIRED'} />
                        <TableRow label="Validity Days" value={candidate.passportData?.validityDays != null ? `${candidate.passportData.validityDays} days` : 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Passport Remark" value={candidate.passportRemark} colSpan={3} isLast />
                    </View>
                </View>

                {/* 6. Work & Education */}
                <Text style={styles.sectionTitle}>6. Work & Education</Text>
                <View style={styles.table}>
                    <View style={styles.tableRow}>
                        <TableRow
                            label="Job Roles"
                            value={(candidate.professionalProfile?.jobRoles || candidate.jobRoles || [])
                                .map(role => typeof role === 'string' ? role : `${role.title} (${role.experienceYears}y - ${role.skillLevel})`)
                                .join(', ')}
                            colSpan={3}
                            isLast
                        />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Experience" value={`${candidate.professionalProfile?.experienceYears || candidate.experienceYears || '0'} years`} />
                        <TableRow label="Target Country" value={candidate.targetCountry || candidate.preferredCountries?.join(', ') || 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Education" value={candidate.professionalProfile?.education?.join(', ') || candidate.education?.join(', ')} colSpan={3} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="School" value={candidate.professionalProfile?.school || candidate.personalInfo?.school || candidate.school} />
                        <TableRow label="GCE O/L Year" value={candidate.professionalProfile?.gceOL?.year || candidate.gceOL?.year} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="GCE A/L Year" value={candidate.professionalProfile?.gceAL?.year || candidate.gceAL?.year} />
                        <TableRow label="Achievements" value={candidate.professionalProfile?.specialAchievements || candidate.specialAchievements} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Training" value={candidate.professionalProfile?.trainingDetails || candidate.trainingDetails} colSpan={3} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Skills" value={candidate.professionalProfile?.skills?.join(', ') || candidate.skills?.join(', ')} colSpan={3} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Preferred Countries" value={candidate.preferredCountries?.join(', ')} colSpan={3} isLast />
                    </View>
                </View>

                {/* 6b. Employment History */}
                {(candidate.professionalProfile?.employmentHistory?.length || candidate.employmentHistory?.length) ? (
                    <>
                        <Text style={styles.sectionTitle}>6b. Employment History</Text>
                        <View style={styles.table}>
                            <View style={[styles.tableRow, styles.tableHeader]}>
                                <Text style={[styles.gridCell, { width: '15%', fontFamily: 'Helvetica-Bold' }]}>Type</Text>
                                <Text style={[styles.gridCell, { width: '25%', fontFamily: 'Helvetica-Bold' }]}>Position</Text>
                                <Text style={[styles.gridCell, { width: '25%', fontFamily: 'Helvetica-Bold' }]}>Company</Text>
                                <Text style={[styles.gridCell, { width: '15%', fontFamily: 'Helvetica-Bold' }]}>Country</Text>
                                <Text style={[styles.gridCell, { width: '20%', fontFamily: 'Helvetica-Bold', borderRightWidth: 0 }]}>Years</Text>
                            </View>
                            {(candidate.professionalProfile?.employmentHistory || candidate.employmentHistory || []).map((emp: any, i: number) => (
                                <View style={styles.tableRow} key={i}>
                                    <Text style={[styles.gridCell, { width: '15%' }]}>{emp.type || '-'}</Text>
                                    <Text style={[styles.gridCell, { width: '25%' }]}>{emp.position || '-'}</Text>
                                    <Text style={[styles.gridCell, { width: '25%' }]}>{emp.companyName || '-'}</Text>
                                    <Text style={[styles.gridCell, { width: '15%' }]}>{emp.country || '-'}</Text>
                                    <Text style={[styles.gridCell, { width: '20%', borderRightWidth: 0 }]}>{emp.years || '-'}</Text>
                                </View>
                            ))}
                        </View>
                    </>
                ) : null}

                {/* 6c. Educational Qualifications */}
                {(candidate.professionalProfile?.educationalQualifications?.length || candidate.educationalQualifications?.length) ? (
                    <>
                        <Text style={styles.sectionTitle}>6c. Qualifications</Text>
                        <View style={styles.table}>
                            <View style={[styles.tableRow, styles.tableHeader]}>
                                <Text style={[styles.gridCell, { width: '30%', fontFamily: 'Helvetica-Bold' }]}>Course</Text>
                                <Text style={[styles.gridCell, { width: '20%', fontFamily: 'Helvetica-Bold' }]}>Level</Text>
                                <Text style={[styles.gridCell, { width: '30%', fontFamily: 'Helvetica-Bold' }]}>Institute</Text>
                                <Text style={[styles.gridCell, { width: '20%', fontFamily: 'Helvetica-Bold', borderRightWidth: 0 }]}>Year</Text>
                            </View>
                            {(candidate.professionalProfile?.educationalQualifications || candidate.educationalQualifications || []).map((eq: any, i: number) => (
                                <View style={styles.tableRow} key={i}>
                                    <Text style={[styles.gridCell, { width: '30%' }]}>{eq.courseName || '-'}</Text>
                                    <Text style={[styles.gridCell, { width: '20%' }]}>{eq.level || '-'}</Text>
                                    <Text style={[styles.gridCell, { width: '30%' }]}>{eq.institute || '-'}</Text>
                                    <Text style={[styles.gridCell, { width: '20%', borderRightWidth: 0 }]}>{eq.year || '-'}</Text>
                                </View>
                            ))}
                        </View>
                    </>
                ) : null}

                {/* 7. Medical & Clearance */}
                <Text style={styles.sectionTitle}>7. Medical & Clearance</Text>
                <View style={styles.table}>
                    <View style={styles.tableRow}>
                        <TableRow label="Medical Status" value={candidate.medicalData?.status || 'N/A'} isSuccess={candidate.medicalData?.status === 'Completed'} isAlert={candidate.medicalData?.status === 'Failed'} />
                        <TableRow label="Medical Expiry" value={candidate.medicalData?.medicalRecords?.[0]?.expiryDate ? new Date(candidate.medicalData.medicalRecords[0].expiryDate).toLocaleDateString() : 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Blood Group" value={candidate.medicalData?.bloodGroup} />
                        <TableRow label="Allergies" value={candidate.medicalData?.allergies} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Scheduled Date" value={candidate.medicalData?.scheduledDate ? new Date(candidate.medicalData.scheduledDate).toLocaleDateString() : 'N/A'} />
                        <TableRow label="Completed Date" value={candidate.medicalData?.completedDate ? new Date(candidate.medicalData.completedDate).toLocaleDateString() : 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Medical Notes" value={candidate.medicalData?.notes} colSpan={3} isLast />
                    </View>
                </View>

                {/* 7b. All Medical Records */}
                {candidate.medicalData?.medicalRecords && candidate.medicalData.medicalRecords.length > 0 ? (
                    <>
                        <Text style={styles.sectionTitle}>7b. Medical Records</Text>
                        <View style={styles.table}>
                            <View style={[styles.tableRow, styles.tableHeader]}>
                                <Text style={[styles.gridCell, { width: '15%', fontFamily: 'Helvetica-Bold' }]}>Date</Text>
                                <Text style={[styles.gridCell, { width: '15%', fontFamily: 'Helvetica-Bold' }]}>Type</Text>
                                <Text style={[styles.gridCell, { width: '15%', fontFamily: 'Helvetica-Bold' }]}>Result</Text>
                                <Text style={[styles.gridCell, { width: '20%', fontFamily: 'Helvetica-Bold' }]}>Clinic</Text>
                                <Text style={[styles.gridCell, { width: '15%', fontFamily: 'Helvetica-Bold' }]}>Expiry</Text>
                                <Text style={[styles.gridCell, { width: '20%', fontFamily: 'Helvetica-Bold', borderRightWidth: 0 }]}>Notes</Text>
                            </View>
                            {candidate.medicalData.medicalRecords.map((rec, i) => (
                                <View style={styles.tableRow} key={i}>
                                    <Text style={[styles.gridCell, { width: '15%' }]}>{rec.date ? new Date(rec.date).toLocaleDateString() : '-'}</Text>
                                    <Text style={[styles.gridCell, { width: '15%' }]}>{rec.type || '-'}</Text>
                                    <Text style={[styles.gridCell, { width: '15%', color: rec.result === 'Pass' ? '#16a34a' : rec.result === 'Fail' ? '#dc2626' : '#0f172a' }]}>{rec.result || '-'}</Text>
                                    <Text style={[styles.gridCell, { width: '20%' }]}>{rec.clinic || '-'}</Text>
                                    <Text style={[styles.gridCell, { width: '15%' }]}>{rec.expiryDate ? new Date(rec.expiryDate).toLocaleDateString() : '-'}</Text>
                                    <Text style={[styles.gridCell, { width: '20%', borderRightWidth: 0 }]}>{rec.notes || '-'}</Text>
                                </View>
                            ))}
                        </View>
                    </>
                ) : null}

                <Text style={styles.sectionTitle}>7c. Police & Security Clearance</Text>
                <View style={styles.table}>
                    <View style={styles.tableRow}>
                        <TableRow label="Police Report" value={candidate.stageData?.policeStatus || 'N/A'} isSuccess={candidate.stageData?.policeStatus === 'Issued'} />
                        <TableRow label="PCC Expiry" value={candidate.pccData?.expiryDate ? new Date(candidate.pccData.expiryDate).toLocaleDateString() : 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="PCC Issued" value={candidate.pccData?.issuedDate ? new Date(candidate.pccData.issuedDate).toLocaleDateString() : 'N/A'} />
                        <TableRow label="PCC Status" value={candidate.pccData?.status} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="PCC Check" value={candidate.pccData?.lastInspectionDate ? new Date(candidate.pccData.lastInspectionDate).toLocaleDateString() : 'N/A'} />
                        <TableRow label="PCC Age" value={candidate.pccData?.ageDays != null ? `${candidate.pccData.ageDays} days` : 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Biometric" value={candidate.slbfeData?.biometricStatus || 'N/A'} isSuccess={candidate.slbfeData?.biometricStatus === 'Completed'} />
                        <TableRow label="Family Consent" value={candidate.slbfeData?.familyConsent?.isGiven ? 'Verified' : 'Pending'} isSuccess={candidate.slbfeData?.familyConsent?.isGiven === true} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Consent By" value={`${candidate.slbfeData?.familyConsent?.signatoryName || 'N/A'} (${candidate.slbfeData?.familyConsent?.signatoryRelation || 'N/A'})`} />
                        <TableRow label="Verified" value={candidate.slbfeData?.familyConsent?.verifiedBy ? `${candidate.slbfeData.familyConsent.verifiedBy} ${candidate.slbfeData.familyConsent.verificationDate ? 'on ' + candidate.slbfeData.familyConsent.verificationDate : ''}` : 'Pending'} isLast />
                    </View>
                </View>

                {/* 8. Embassy & Visa */}
                <Text style={styles.sectionTitle}>8. Embassy & Visa</Text>
                <View style={styles.table}>
                    <View style={styles.tableRow}>
                        <TableRow label="E No / SE No" value={`${candidate.embassyDetails?.eNo || 'N/A'} / ${candidate.embassyDetails?.seNo || 'N/A'}`} />
                        <TableRow label="Applied Date" value={candidate.embassyDetails?.appliedDate ? new Date(candidate.embassyDetails.appliedDate).toLocaleDateString() : 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Appointment" value={candidate.embassyDetails?.appointmentDate ? new Date(candidate.embassyDetails.appointmentDate).toLocaleString() : 'N/A'} />
                        <TableRow label="Stamp Date" value={candidate.embassyDetails?.stampDate ? new Date(candidate.embassyDetails.stampDate).toLocaleDateString() : 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Result" value={candidate.embassyDetails?.stampResult || 'N/A'} isSuccess={candidate.embassyDetails?.stampResult === 'Stamped'} isAlert={candidate.embassyDetails?.stampResult === 'Rejected'} />
                        <TableRow label="Reject Reason" value={candidate.embassyDetails?.rejectReason} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Awareness Date" value={candidate.embassyDetails?.awarenessProgramDate ? new Date(candidate.embassyDetails.awarenessProgramDate).toLocaleDateString() : 'N/A'} />
                        <TableRow label="Awareness Signed" value={candidate.embassyDetails?.awarenessProgramSigned ? 'Yes' : 'No'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Visa" value={candidate.stageData?.visaStatus || 'N/A'} isSuccess={candidate.stageData?.visaStatus === 'Approved'} />
                        <TableRow label="Work Permit" value={candidate.stageData?.wpReferenceNumber || 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="USD Rate EMB" value={candidate.usdRateEmb ? `${candidate.usdRateEmb}` : 'N/A'} />
                        <TableRow label="USD Rate F/A" value={candidate.usdRateFA ? `${candidate.usdRateFA}` : 'N/A'} isLast />
                    </View>
                </View>

                {/* 9. SLBFE & Departure */}
                <Text style={styles.sectionTitle}>9. SLBFE & Departure</Text>
                <View style={styles.table}>
                    <View style={styles.tableRow}>
                        <TableRow label="SLBFE No" value={candidate.slbfeData?.registrationNumber || 'N/A'} />
                        <TableRow label="SLBFE Reg Date" value={candidate.slbfeData?.registrationDate ? new Date(candidate.slbfeData.registrationDate).toLocaleDateString() : 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Training Institute" value={candidate.slbfeData?.trainingInstitute || 'N/A'} />
                        <TableRow label="Certificate No" value={candidate.slbfeData?.trainingCertificateNo || 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Training Date" value={candidate.slbfeData?.trainingDate ? new Date(candidate.slbfeData.trainingDate).toLocaleDateString() : 'N/A'} />
                        <TableRow label="Agreement Status" value={candidate.slbfeData?.agreementStatus} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Insurance" value={`${candidate.slbfeData?.insuranceProvider || 'N/A'} - Policy: ${candidate.slbfeData?.insurancePolicyNumber || 'N/A'}`} colSpan={3} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Insurance Expiry" value={candidate.slbfeData?.insuranceExpiryDate ? new Date(candidate.slbfeData.insuranceExpiryDate).toLocaleDateString() : 'N/A'} />
                        <TableRow label="Premium" value={candidate.slbfeData?.insurancePremium ? `LKR ${candidate.slbfeData.insurancePremium.toLocaleString()}` : 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Deployment Approval" value={candidate.slbfeData?.deploymentApprovalDate ? new Date(candidate.slbfeData.deploymentApprovalDate).toLocaleDateString() : 'N/A'} />
                        <TableRow label="Departure Date" value={candidate.departureDate ? new Date(candidate.departureDate).toLocaleDateString() : 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Travel Insurance" value={`Policy: ${candidate.stageData?.travelInsurancePolicyNumber || 'N/A'}`} />
                        <TableRow label="Coverage End" value={candidate.stageData?.travelInsuranceCoverageEndDate ? new Date(candidate.stageData.travelInsuranceCoverageEndDate).toLocaleDateString() : 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Flight No" value={candidate.stageData?.flightNumber || 'N/A'} />
                        <TableRow label="Flight PNR" value={candidate.stageData?.flightPNR || 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Departure Time" value={candidate.stageData?.flightDepartureTime ? new Date(candidate.stageData.flightDepartureTime).toLocaleString() : 'N/A'} colSpan={3} isLast />
                    </View>
                </View>

            </Page>

            {/* FINANCIALS & DOCUMENTS */}
            <Page size="A4" style={styles.page}>
                <Header candidate={candidate} reportId={reportId} />
                <Footer generatedBy={generatedBy} />
                <Watermark />

                <Text style={styles.sectionTitle}>10. Payments</Text>
                {candidate.advancePayments && candidate.advancePayments.length > 0 ? (
                    <View style={styles.table}>
                        <View style={[styles.tableRow, styles.tableHeader]}>
                            <Text style={[styles.gridCell, { width: '15%', fontFamily: 'Helvetica-Bold' }]}>Type</Text>
                            <Text style={[styles.gridCell, { width: '15%', fontFamily: 'Helvetica-Bold' }]}>Invoice</Text>
                            <Text style={[styles.gridCell, { width: '15%', fontFamily: 'Helvetica-Bold' }]}>Sign Date</Text>
                            <Text style={[styles.gridCell, { width: '15%', fontFamily: 'Helvetica-Bold' }]}>Amount</Text>
                            <Text style={[styles.gridCell, { width: '15%', fontFamily: 'Helvetica-Bold' }]}>Informed</Text>
                            <Text style={[styles.gridCell, { width: '25%', fontFamily: 'Helvetica-Bold', borderRightWidth: 0 }]}>Remarks</Text>
                        </View>
                        {candidate.advancePayments.map((payment: any, index: number) => (
                            <View style={styles.tableRow} key={index}>
                                <Text style={[styles.gridCell, { width: '15%' }]}>{payment.type}</Text>
                                <Text style={[styles.gridCell, { width: '15%' }]}>{payment.invoiceNo || '-'}</Text>
                                <Text style={[styles.gridCell, { width: '15%' }]}>{payment.signDate ? new Date(payment.signDate).toLocaleDateString() : '-'}</Text>
                                <Text style={[styles.gridCell, { width: '15%' }]}>{payment.amount ? `LKR ${payment.amount.toLocaleString()}` : '-'}</Text>
                                <Text style={[styles.gridCell, { width: '15%' }]}>{payment.informed ? `Yes (${payment.informedDate || ''})` : 'No'}</Text>
                                <Text style={[styles.gridCell, { width: '25%', borderRightWidth: 0 }]}>{payment.remarks || '-'}</Text>
                            </View>
                        ))}
                    </View>
                ) : (
                    <View style={styles.table}><View style={styles.tableRow}><Text style={[styles.gridCell, { width: '100%', borderRightWidth: 0 }]}>No payments recorded.</Text></View></View>
                )}

                <Text style={styles.sectionTitle}>11. Documents</Text>
                {candidate.documents && candidate.documents.length > 0 ? (
                    <View style={styles.table}>
                        <View style={[styles.tableRow, styles.tableHeader]}>
                            <Text style={[styles.gridCell, { width: '30%', fontFamily: 'Helvetica-Bold' }]}>Document Type</Text>
                            <Text style={[styles.gridCell, { width: '30%', fontFamily: 'Helvetica-Bold' }]}>Category</Text>
                            <Text style={[styles.gridCell, { width: '20%', fontFamily: 'Helvetica-Bold' }]}>Status</Text>
                            <Text style={[styles.gridCell, { width: '20%', fontFamily: 'Helvetica-Bold', borderRightWidth: 0 }]}>Upload Date</Text>
                        </View>
                        {candidate.documents.map((doc, index) => (
                            <React.Fragment key={index}>
                                <View style={styles.tableRow}>
                                    <Text style={[styles.gridCell, { width: '30%' }]}>{doc.type}</Text>
                                    <Text style={[styles.gridCell, { width: '30%' }]}>{doc.category}</Text>
                                    <Text style={[styles.gridCell, { width: '20%', color: doc.status === 'Rejected' ? '#dc2626' : doc.status === 'Approved' ? '#16a34a' : '#0f172a' }]}>{doc.status}</Text>
                                    <Text style={[styles.gridCell, { width: '20%', borderRightWidth: 0 }]}>{doc.uploadedAt ? new Date(doc.uploadedAt).toLocaleDateString() : '-'}</Text>
                                </View>
                                {doc.status === 'Rejected' && doc.rejectionReason && (
                                    <View style={styles.tableRow}>
                                        <Text style={[styles.gridCell, { width: '30%' }]}></Text>
                                        <Text style={[styles.gridCell, { width: '70%', borderRightWidth: 0, color: '#dc2626' }]}>Reason: {doc.rejectionReason}</Text>
                                    </View>
                                )}
                            </React.Fragment>
                        ))}
                    </View>
                ) : (
                    <View style={styles.table}><View style={styles.tableRow}><Text style={[styles.gridCell, { width: '100%', borderRightWidth: 0 }]}>No documents uploaded.</Text></View></View>
                )}

                {/* 12. Officer Notes */}
                <Text style={styles.sectionTitle}>12. Officer Notes</Text>
                {candidate.comments && candidate.comments.length > 0 ? (
                    <View style={styles.table}>
                        <View style={[styles.tableRow, styles.tableHeader]}>
                            <Text style={[styles.gridCell, { width: '20%', fontFamily: 'Helvetica-Bold' }]}>Timestamp</Text>
                            <Text style={[styles.gridCell, { width: '20%', fontFamily: 'Helvetica-Bold' }]}>Officer</Text>
                            <Text style={[styles.gridCell, { width: '60%', fontFamily: 'Helvetica-Bold', borderRightWidth: 0 }]}>Comment</Text>
                        </View>
                        {candidate.comments.map((comment, index) => (
                            <View style={styles.tableRow} key={index}>
                                <Text style={[styles.gridCell, { width: '20%' }]}>{new Date(comment.timestamp).toLocaleString()}</Text>
                                <Text style={[styles.gridCell, { width: '20%' }]}>{comment.author}</Text>
                                <Text style={[styles.gridCell, { width: '60%', borderRightWidth: 0 }]}>{comment.text}</Text>
                            </View>
                        ))}
                    </View>
                ) : (
                    <View style={styles.table}><View style={styles.tableRow}><Text style={[styles.gridCell, { width: '100%', borderRightWidth: 0 }]}>No comments recorded.</Text></View></View>
                )}

                {/* 13. Activity Log */}
                <Text style={styles.sectionTitle}>13. Activity Log</Text>
                {candidate.remarkLog && candidate.remarkLog.length > 0 ? (
                    <View style={styles.table}>
                        <View style={[styles.tableRow, styles.tableHeader]}>
                            <Text style={[styles.gridCell, { width: '20%', fontFamily: 'Helvetica-Bold' }]}>Date</Text>
                            <Text style={[styles.gridCell, { width: '55%', fontFamily: 'Helvetica-Bold' }]}>Remark</Text>
                            <Text style={[styles.gridCell, { width: '25%', fontFamily: 'Helvetica-Bold', borderRightWidth: 0 }]}>Status</Text>
                        </View>
                        {candidate.remarkLog.map((entry, index) => (
                            <View style={styles.tableRow} key={index}>
                                <Text style={[styles.gridCell, { width: '20%' }]}>{entry.date ? new Date(entry.date).toLocaleDateString() : '-'}</Text>
                                <Text style={[styles.gridCell, { width: '55%' }]}>{entry.remark}</Text>
                                <Text style={[styles.gridCell, { width: '25%', borderRightWidth: 0 }]}>{entry.note || '-'}</Text>
                            </View>
                        ))}
                    </View>
                ) : (
                    <View style={styles.table}><View style={styles.tableRow}><Text style={[styles.gridCell, { width: '100%', borderRightWidth: 0 }]}>No activity log entries.</Text></View></View>
                )}

            </Page>

            {/* PAGE: Milestones, Stage History, Audit */}
            <Page size="A4" style={styles.page}>
                <Header candidate={candidate} reportId={reportId} />
                <Footer generatedBy={generatedBy} />
                <Watermark />

                {/* 14. Workflow Milestones */}
                <Text style={styles.sectionTitle}>14. Workflow Milestones</Text>
                <View style={styles.table}>
                    <View style={styles.tableRow}>
                        <TableRow label="Offer Applied" value={candidate.workflowMilestones?.offerAppliedDate ? new Date(candidate.workflowMilestones.offerAppliedDate).toLocaleDateString() : 'N/A'} />
                        <TableRow label="Offer Received" value={candidate.workflowMilestones?.offerReceivedDate ? new Date(candidate.workflowMilestones.offerReceivedDate).toLocaleDateString() : 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="WP Applied" value={candidate.workflowMilestones?.wpAppliedDate ? new Date(candidate.workflowMilestones.wpAppliedDate).toLocaleDateString() : 'N/A'} />
                        <TableRow label="WP Received" value={candidate.workflowMilestones?.wpReceivedDate ? new Date(candidate.workflowMilestones.wpReceivedDate).toLocaleDateString() : 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Embassy Applied" value={candidate.workflowMilestones?.embAppliedDate ? new Date(candidate.workflowMilestones.embAppliedDate).toLocaleDateString() : 'N/A'} />
                        <TableRow label="Embassy Appt" value={candidate.workflowMilestones?.embAppointmentDate ? new Date(candidate.workflowMilestones.embAppointmentDate).toLocaleDateString() : 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Stamp/Reject" value={candidate.workflowMilestones?.stampRejectDate ? new Date(candidate.workflowMilestones.stampRejectDate).toLocaleDateString() : 'N/A'} />
                        <TableRow label="Stamp Result" value={candidate.workflowMilestones?.stampResult || 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="SLBFE Training" value={candidate.workflowMilestones?.slbfeTrainingDate ? new Date(candidate.workflowMilestones.slbfeTrainingDate).toLocaleDateString() : 'N/A'} />
                        <TableRow label="SLBFE Reg" value={candidate.workflowMilestones?.slbfeRegistrationDate ? new Date(candidate.workflowMilestones.slbfeRegistrationDate).toLocaleDateString() : 'N/A'} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Departure" value={candidate.workflowMilestones?.departureDate ? new Date(candidate.workflowMilestones.departureDate).toLocaleDateString() : 'N/A'} colSpan={3} isLast />
                    </View>
                </View>

                {/* 15. Stage History */}
                <Text style={styles.sectionTitle}>15. Stage History</Text>
                {candidate.stageHistory && candidate.stageHistory.length > 0 ? (
                    <View style={styles.table}>
                        <View style={[styles.tableRow, styles.tableHeader]}>
                            <Text style={[styles.gridCell, { width: '30%', fontFamily: 'Helvetica-Bold' }]}>Stage</Text>
                            <Text style={[styles.gridCell, { width: '30%', fontFamily: 'Helvetica-Bold' }]}>Date</Text>
                            <Text style={[styles.gridCell, { width: '40%', fontFamily: 'Helvetica-Bold', borderRightWidth: 0 }]}>Notes</Text>
                        </View>
                        {candidate.stageHistory.map((sh, index) => (
                            <View style={styles.tableRow} key={index}>
                                <Text style={[styles.gridCell, { width: '30%' }]}>{sh.stage}</Text>
                                <Text style={[styles.gridCell, { width: '30%' }]}>{sh.timestamp ? new Date(sh.timestamp).toLocaleString() : '-'}</Text>
                                <Text style={[styles.gridCell, { width: '40%', borderRightWidth: 0 }]}>{sh.notes || '-'}</Text>
                            </View>
                        ))}
                    </View>
                ) : (
                    <View style={styles.table}><View style={styles.tableRow}><Text style={[styles.gridCell, { width: '100%', borderRightWidth: 0 }]}>No stage history.</Text></View></View>
                )}

                {/* 16. System Audit */}
                <Text style={styles.sectionTitle}>16. System Record</Text>
                <View style={styles.table}>
                    <View style={styles.tableRow}>
                        <TableRow label="Created" value={candidate.audit?.createdAt ? new Date(candidate.audit.createdAt).toLocaleString() : 'N/A'} />
                        <TableRow label="Created By" value={candidate.audit?.createdBy} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Last Updated" value={candidate.audit?.updatedAt ? new Date(candidate.audit.updatedAt).toLocaleString() : 'N/A'} />
                        <TableRow label="Updated By" value={candidate.audit?.updatedBy} isLast />
                    </View>
                    <View style={styles.tableRow}>
                        <TableRow label="Version" value={candidate.audit?.version} />
                        <TableRow label="Source" value={candidate.registrationSource} isLast />
                    </View>
                    {candidate.audit?.deletedAt && (
                        <View style={styles.tableRow}>
                            <TableRow label="Deleted At" value={new Date(candidate.audit.deletedAt).toLocaleString()} colSpan={3} isAlert isLast />
                        </View>
                    )}
                </View>

                {/* 17. Multimedia & External Links */}
                {(candidate.stageData?.workingVideoLink || candidate.stageData?.selfIntroductionVideoLink || candidate.stageData?.additionalVideoLinks?.length) ? (
                    <>
                        <Text style={styles.sectionTitle}>17. Multimedia & Links</Text>
                        <View style={styles.table}>
                            {candidate.stageData.selfIntroductionVideoLink && (
                                <View style={styles.tableRow}>
                                    <TableRow label="Self Intro Video" value={candidate.stageData.selfIntroductionVideoLink} colSpan={3} isLast />
                                </View>
                            )}
                            {candidate.stageData.workingVideoLink && (
                                <View style={styles.tableRow}>
                                    <TableRow label="Working Video" value={candidate.stageData.workingVideoLink} colSpan={3} isLast />
                                </View>
                            )}
                            {candidate.stageData.additionalVideoLinks?.map((link, i) => (
                                <View style={styles.tableRow} key={i}>
                                    <TableRow label={`Extra Video ${i + 1}`} value={link} colSpan={3} isLast />
                                </View>
                            ))}
                        </View>
                    </>
                ) : null}

                {/* 18. Compliance Flags */}
                {candidate.complianceFlags && candidate.complianceFlags.length > 0 ? (
                    <>
                        <Text style={styles.sectionTitle}>18. Compliance Flags</Text>
                        <View style={styles.table}>
                            <View style={[styles.tableRow, styles.tableHeader]}>
                                <Text style={[styles.gridCell, { width: '15%', fontFamily: 'Helvetica-Bold' }]}>Type</Text>
                                <Text style={[styles.gridCell, { width: '15%', fontFamily: 'Helvetica-Bold' }]}>Severity</Text>
                                <Text style={[styles.gridCell, { width: '40%', fontFamily: 'Helvetica-Bold' }]}>Reason</Text>
                                <Text style={[styles.gridCell, { width: '15%', fontFamily: 'Helvetica-Bold' }]}>Status</Text>
                                <Text style={[styles.gridCell, { width: '15%', fontFamily: 'Helvetica-Bold', borderRightWidth: 0 }]}>Created</Text>
                            </View>
                            {candidate.complianceFlags.map((flag, i) => (
                                <View style={styles.tableRow} key={i}>
                                    <Text style={[styles.gridCell, { width: '15%' }]}>{flag.type}</Text>
                                    <Text style={[styles.gridCell, { width: '15%', color: flag.severity === 'CRITICAL' ? '#dc2626' : '#ea580c' }]}>{flag.severity}</Text>
                                    <Text style={[styles.gridCell, { width: '40%' }]}>{flag.reason}</Text>
                                    <Text style={[styles.gridCell, { width: '15%', color: flag.isResolved ? '#16a34a' : '#0f172a' }]}>{flag.isResolved ? 'Resolved' : 'Active'}</Text>
                                    <Text style={[styles.gridCell, { width: '15%', borderRightWidth: 0 }]}>{new Date(flag.createdAt).toLocaleDateString()}</Text>
                                </View>
                            ))}
                        </View>
                    </>
                ) : null}

                <View style={{ marginTop: 25, borderTopWidth: 1, borderTopColor: '#000000', paddingTop: 10 }}>
                    <Text style={{ fontSize: 8, fontStyle: 'italic', color: '#475569' }}>
                        This report is a system-generated extract for candidate {candidate.regNo || candidate.candidateCode}. All data is sourced from the official database records.
                    </Text>
                    <View style={{ flexDirection: 'row', marginTop: 30 }}>
                        <View style={{ width: '50%' }}>
                            <View style={{ borderBottomWidth: 1, borderBottomColor: '#000', width: 150, marginBottom: 5 }} />
                            <Text style={{ fontSize: 9 }}>Officer Signature</Text>
                            <Text style={{ fontSize: 8, color: '#64748b', marginTop: 3 }}>Date: ________________</Text>
                        </View>
                    </View>
                </View>

            </Page>
        </Document>
    );
};
