import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: 'Helvetica',
    fontSize: 9,
    color: '#1e293b', // slate-800
    backgroundColor: '#ffffff',
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottomWidth: 2,
    borderBottomColor: '#0f172a',
    paddingBottom: 10,
    marginBottom: 15,
  },
  logo: {
    width: 280,
    height: 100,
    objectFit: 'contain',
    alignSelf: 'flex-start',
  },
  headerText: {
    textAlign: 'right',
  },
  docTitle: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    color: '#0f172a',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  docMeta: {
    fontSize: 8,
    color: '#64748b',
    marginTop: 4,
    textTransform: 'uppercase',
  },
  docMetaBold: {
    fontSize: 10,
    color: '#0f172a',
    fontFamily: 'Helvetica-Bold',
    marginTop: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: '#ffffff',
    backgroundColor: '#0f172a',
    paddingVertical: 4,
    paddingHorizontal: 8,
    marginTop: 15,
    marginBottom: 5,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  subSectionTitle: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: '#0f172a',
    borderBottomWidth: 1,
    borderBottomColor: '#cbd5e1',
    paddingBottom: 2,
    marginTop: 10,
    marginBottom: 5,
    textTransform: 'uppercase',
  },
  table: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#94a3b8',
    marginBottom: 5,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#cbd5e1',
    minHeight: 18,
    alignItems: 'center',
  },
  tableHeader: {
    backgroundColor: '#f1f5f9',
  },
  tableCellLabel: {
    padding: 4,
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: '#475569',
    backgroundColor: '#f8fafc',
    borderRightWidth: 1,
    borderRightColor: '#cbd5e1',
    width: '25%',
  },
  tableCellValue: {
    padding: 4,
    fontSize: 8,
    color: '#0f172a',
    width: '25%',
    borderRightWidth: 1,
    borderRightColor: '#cbd5e1',
  },
  lastCell: { borderRightWidth: 0 },
  colFull: { width: '75%', borderRightWidth: 0 },
  colHalf: { width: '50%' },
  colThirdLabel: { width: '15%', backgroundColor: '#f8fafc', padding: 4, fontSize: 8, fontFamily: 'Helvetica-Bold', color: '#475569', borderRightWidth: 1, borderRightColor: '#cbd5e1' },
  colThirdValue: { width: '18.33%', padding: 4, fontSize: 8, color: '#0f172a', borderRightWidth: 1, borderRightColor: '#cbd5e1' },
  gridCell: {
    padding: 4,
    fontSize: 8,
    borderRightWidth: 1,
    borderRightColor: '#cbd5e1',
    justifyContent: 'center',
  },
  gridHeaderItem: {
    fontFamily: 'Helvetica-Bold',
    backgroundColor: '#f1f5f9',
    color: '#334155',
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 30,
    right: 30,
    borderTopWidth: 1,
    borderTopColor: '#94a3b8',
    paddingTop: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerText: {
    fontSize: 7,
    color: '#64748b',
  },
  watermark: {
    position: 'absolute',
    top: '20%',
    left: '10%',
    width: 450,
    height: 450,
    opacity: 0.035,
    zIndex: -1,
  },
  alertText: {
    color: '#dc2626',
    fontFamily: 'Helvetica-Bold',
  },
  successText: {
    color: '#16a34a',
    fontFamily: 'Helvetica-Bold',
  },
  boldValue: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 9,
    color: '#0f172a',
  }
});
